### ISSUE TITLE
What's going on here?

### ISSUE THREAD

**Issue by joshuapetryk** [Azure/azure-functions-java-core-library#6]
I see this repo was split out from azure-functions-java-library: https://github.com/Azure/azure-functions-java-library/commit/8de47bab44bd425614360cd6a5784637b1031420

I'm having a hard time following what's going on, any docs or discussion to provide some context?

I'm trying to develop Java functions and trying to understand limitations when compared to C# but I'm having trouble finding various pieces of source code.

**Comment by kaibocai** [comment]
Hi @joshuapetryk , thanks for reaching out and feedback. We split this repo from azure-functions-java-library cause it decouple azure-functions-java-worker and azure-functions-java-library which allow us to do separate release and update. 

Usually you don't need to care about this repo. The one you will directly depend on is [azure-functions-java-library](https://github.com/Azure/azure-functions-java-library).

Usually, when write your own java function code you only need azure-functions-java-library as a dependency. 
All of other part source code you can find it here
[azure-functions-java-worker](https://github.com/Azure/azure-functions-java-worker) the worker that will act as a container to serve and run the java function you write. 
[azure-functions-java-library](https://github.com/Azure/azure-functions-java-library), it contains all the triggers and bindings you need to write your java function. 

Here is some quick start documents that should help
[Quickstart: Create a Java function in Azure from the command line](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-java?tabs=bash%2Cazure-cli%2Cbrowser)

[Repo of different samples java function](https://github.com/Azure-Samples/azure-functions-samples-java)

Please let me know your feedback if you have more, we appreciate all of them. Thank.
